"use client";
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/o0FHYhLTmVu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"
import Link from "next/link"
import Image from 'next/image'
import { Button } from "@/components/ui/button"
import { useRouter } from "next/navigation";
import { acceptProduct } from "@/app/actions/acceptProduct";

export function Submissions({data,updatePending}) {
  const router = useRouter()
  return (
    (<Card className="w-full max-w-3xl mx-auto">
      <CardHeader>
        <CardTitle>Moderator Panel</CardTitle>
        <CardDescription>Review and approve product submissions</CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        <div className="grid gap-4">
          <div
            className="grid items-center gap-4 px-4 py-3 rounded-lg bg-gray-100 dark:bg-gray-800">
            <SearchIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            <Input
              className="w-full appearance-none bg-transparent border-0 box-border outline-none"
              placeholder="Search product submissions..."
              type="search" />
          </div>
          <Card>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Product</TableHead>
                    <TableHead>Submitted by</TableHead>
                    <TableHead className="hidden md:table-cell">Submission date</TableHead>
                    <TableHead className="hidden md:table-cell">Actions</TableHead>
                    {/* <TableHead className="w-12" /> */}
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {
                    data.length===0?
                    (
                      <h1 className="py-5 text-center w-[100%]">nothing to show</h1>
                    )
                    :
                    data.map((product)=>(
                      <TableRow className="odd:bg-gray-100 cursor-pointer" onClick={()=>router.push(`moderator/product/${product.product_id}`)}>
                        <TableCell className="font-semibold">{product.name}</TableCell>
                        <TableCell>{product.posted_by}</TableCell>
                        <TableCell className="hidden md:table-cell">{product.created_at.replace("T"," | ").split("Z").join(" ").slice(0,-5)}</TableCell>
                        <TableCell className="flex items-center">
                          <button className="z-10" onClick={async(e)=>{
                                e.stopPropagation();
                                await acceptProduct(product.product_id);
                                await updatePending("pending")
                              }}>
                              <Image src={"/approve.png"} width={22} height={22}/>
                          </button>
                          <button className="ml-4 z-10" onClick={async(e)=>{
                            e.stopPropagation();
                            await rejectProduct(product.product_id);
                            await updatePending("pending")
                              }}>
                              <Image src={"/reject.png"} width={22} height={22}/>
                          </button>
                        </TableCell>
                          {/* <Link href={`/moderator/product/${product.product_id}`} style={{width:"100%"}}>
                          </Link>  */}
                      </TableRow>
                    ))
                  }
                  {/* <TableRow>
                    <TableCell className="flex w-12 items-start">
                      <Checkbox className="mt-1" id="submission-2" />
                    </TableCell>
                    <TableCell className="font-semibold">Aqua Filters</TableCell>
                    <TableCell>hydra@example.com</TableCell>
                    <TableCell className="hidden md:table-cell">2023-10-12 15:32</TableCell>
                    <TableCell className="flex w-12 items-center">
                      <Link
                        className="rounded-lg border border-gray-200 hover:border-gray-900 p-2 transition-colors dark:hover:border-gray-50 dark:border-gray-800"
                        href="#">
                        <ExternalLinkIcon className="w-3 h-3" />
                        <span className="sr-only">View submission</span>
                      </Link>
                    </TableCell>
                  </TableRow>
                  <TableRow className="bg-gray-100 dark:bg-gray-800">
                    <TableCell className="flex w-12 items-start">
                      <Checkbox className="mt-1" id="submission-3" />
                    </TableCell>
                    <TableCell className="font-semibold">Eco Planters</TableCell>
                    <TableCell>greengrowth@example.com</TableCell>
                    <TableCell className="hidden md:table-cell">2023-10-12 15:32</TableCell>
                    <TableCell className="flex w-12 items-center">
                      <Link
                        className="rounded-lg border border-gray-200 hover:border-gray-900 p-2 transition-colors dark:hover:border-gray-50 dark:border-gray-800"
                        href="#">
                        <ExternalLinkIcon className="w-3 h-3" />
                        <span className="sr-only">View submission</span>
                      </Link>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="flex w-12 items-start">
                      <Checkbox className="mt-1" id="submission-4" />
                    </TableCell>
                    <TableCell className="font-semibold">Zest Juicers</TableCell>
                    <TableCell>fresh@example.com</TableCell>
                    <TableCell className="hidden md:table-cell">2023-10-12 15:32</TableCell>
                    <TableCell className="flex w-12 items-center">
                      <Link
                        className="rounded-lg border border-gray-200 hover:border-gray-900 p-2 transition-colors dark:hover:border-gray-50 dark:border-gray-800"
                        href="#">
                        <ExternalLinkIcon className="w-3 h-3" />
                        <span className="sr-only">View submission</span>
                      </Link>
                    </TableCell>
                  </TableRow>
                  <TableRow className="bg-gray-100 dark:bg-gray-800">
                    <TableCell className="flex w-12 items-start">
                      <Checkbox className="mt-1" id="submission-5" />
                    </TableCell>
                    <TableCell className="font-semibold">Flexi Wearables</TableCell>
                    <TableCell>vitality@example.com</TableCell>
                    <TableCell className="hidden md:table-cell">2023-10-12 15:32</TableCell>
                    <TableCell className="flex w-12 items-center">
                      <Link
                        className="rounded-lg border border-gray-200 hover:border-gray-900 p-2 transition-colors dark:hover:border-gray-50 dark:border-gray-800"
                        href="#">
                        <ExternalLinkIcon className="w-3 h-3" />
                        <span className="sr-only">View submission</span>
                      </Link>
                    </TableCell>
                  </TableRow> */}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <div className="flex items-center justify-between px-4 py-3">
            <div className="text-sm text-gray-500 dark:text-gray-400">Showing 1 to 5 of 5 entries</div>
            <div className="flex items-center gap-2 text-sm">
              <Button className="rounded-full" size="icon" variant="outline">
                <ChevronLeftIcon className="h-4 w-4" />
                <span className="sr-only">Previous</span>
              </Button>
              <Button className="rounded-full" size="icon" variant="outline">
                <ChevronRightIcon className="h-4 w-4" />
                <span className="sr-only">Next</span>
              </Button>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function ExternalLinkIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
      <polyline points="15 3 21 3 21 9" />
      <line x1="10" x2="21" y1="14" y2="3" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
